### PR TITLE
Install process tidy up

### PR DESCRIPTION
**Pull request by sina-masoud-ansari**
Hi all, 

This pull request includes some tidying of the Dockerfile and requirements.txt. I've been testing it as part of an automated pymarl deployment process over at [https://github.com/sina-masoud-ansari/pymarl-deploy](https://github.com/sina-masoud-ansari/pymarl-deploy)

I've tested the updated Docker build with a Titan RTX, the image below is from 12 runs of qmix_smac on the 3m map, vanilla settings.

RTX_Titan-MMM

It seems to converge faster than the results in the SMAC paper, I'm curious if you have any insight as to why. I have yet to look into the code but I thought perhaps convergence would be somewhat hardware independent e.g. replay buffer size not being device dependent

Thanks for making this code public. I'll be working on this  over the next couple of years as part of a Master's project. I've started tracking some issues on [my fork](https://github.com/sina-masoud-ansari/pymarl) and hopefully will be in touch again with fixes.

Cheers

### CODE REVIEW

**Comment by GoingMyWay** [comment]
@sina-masoud-ansari Hi, for MMM, as shown above, you trained 10 Million steps, how many days it will cost？

**Comment by sina-masoud-ansari** [comment]
@GoingMyWay I think 10 million is unnecessary, 2 million is enough and that usually takes a 1 day. You can increase batch_size_run to speed things up, I've seen MMM stable with batch_size_run=8, so assuming you have a few CPUs it should be done in a few hours.

**Comment by sina-masoud-ansari** [comment]
Just cancelling this pull request as it is from my forks master which should not be integrated upstream.

**Comment by GoingMyWay** [comment]
> @GoingMyWay I think 10 million is unnecessary, 2 million is enough and that usually takes a 1 day. You can increase batch_size_run to speed things up, I've seen MMM stable with batch_size_run=8, so assuming you have a few CPUs it should be done in a few hours.

Thanks, I will try to use `batch_size_run=8` to speed up the training process.

**Pull request closed without merging**
